Numpy

In [1]:
import numpy as np

In [14]:
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Generating random integers from 0 to 1.

In [11]:
np.random.rand(2)

array([0.82650532, 0.56473768])

Generating random continuous numbers from a normal distribution 

In [13]:
np.random.randn(10)

array([ 1.79630537,  1.26389197, -0.6171143 , -1.36807246, -0.52689459,
        0.47249394,  1.5444536 ,  1.01427397,  0.09921068, -1.08071915])

In [21]:
k = np.random.randint(1,100,20)

In [22]:
k.shape

(20,)

In [23]:
k

array([ 1, 88,  5, 34, 84, 82, 54, 13, 24, 27, 15, 57, 82,  6, 87, 90, 99,
       15, 68, 11])

In [24]:
k.reshape(10,2)

array([[ 1, 88],
       [ 5, 34],
       [84, 82],
       [54, 13],
       [24, 27],
       [15, 57],
       [82,  6],
       [87, 90],
       [99, 15],
       [68, 11]])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [26]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [27]:
np.arange(30,100,3)

array([30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78,
       81, 84, 87, 90, 93, 96, 99])

In [28]:
sample = np.random.randint(1,100,20)

In [30]:
sample.max()

98

In [31]:
sample.min()

3

In [32]:
sample.argmax()

3

In [35]:
sample

array([ 3, 41, 42, 98, 71, 45, 21, 56, 62, 37, 88, 68, 12, 10, 37, 41, 34,
       43, 47, 48])

In [36]:
sample.argmin()

0

In [37]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])



In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[:,0]

array([ 5, 20, 35])

In [42]:
arr_2d[1,:]

array([20, 25, 30])

In [44]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [46]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [47]:
array = np.arange(1,11)

In [48]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
array[array >= 6]

array([ 6,  7,  8,  9, 10])

In [53]:
arr_2d = np.arange(50).reshape(5,10)

In [55]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [ ]:
arr_2d